// Generated by CoffeeScript 1.3.3
(function() {

  describe('Base behavior', function() {
    return it('must be true', function() {
      return expect(true).toBeTruthy();
    });
  });

}).call(this);
