// Generated by CoffeeScript 1.4.0
(function() {

  describe('HTML5 Sortable', function() {
    var cleanSandbox, loadFixture;
    cleanSandbox = function() {
      return TestHelper.cleanSandbox();
    };
    loadFixture = function(name) {
      return TestHelper.loadFixture(name);
    };
    beforeEach(function() {
      return this.sandbox = cleanSandbox();
    });
    return describe('fixture system', function() {
      it('starts off with a clean sandbox and can be cleaned up', function() {
        expect($('#sandbox').html()).to.be.empty;
        loadFixture('sortableList');
        expect($('#sandbox').html()).to.not.be.empty;
        cleanSandbox();
        return expect($('#sandbox').html()).to.be.empty;
      });
      return it('loads an HTML fragment into the sandbox', function() {
        var sortable;
        this.sandbox = loadFixture('sortableList');
        sortable = this.sandbox.find('.sortable');
        return expect(sortable.length).to.not.be.empty;
      });
    });
  });

}).call(this);
