// Generated by CoffeeScript 1.4.0
(function() {

  describe('Base behavior', function() {
    return it('must be true', function() {
      return expect(false).to.be["true"];
    });
  });

}).call(this);
