// Generated by CoffeeScript 1.4.0
(function() {
  var _fixtureSrings;

  _fixtureSrings = {
    sortableList: "<section id=\"sortable-list\">\n  <h2>Sortable List</h2>\n  <ul class=\"sortable\">\n    <li>Item 1</li>\n    <li>Item 2</li>\n    <li>Item 3</li>\n    <li>Item 4</li>\n    <li>Item 5</li>\n    <li>Item 6</li>\n  </ul>\n</section>",
    sortableGrid: "<section id=\"sortable-grid\">\n  <h2>Sortable Grid</h2>\n  <ul class=\"sortable sortable-grid\">\n    <li>Item 1</li>\n    <li>Item 2</li>\n    <li>Item 3</li>\n    <li>Item 4</li>\n    <li>Item 5</li>\n    <li>Item 6</li>\n  </ul>\n</section>",
    sortableWithExcludes: "<section id=\"sortable-with-excludes\">\n  <h2>Sortable With Excludes</h2>\n  <ul class=\"sortable sortable-with-excludes\">\n    <li>Item 1</li>\n    <li>Item 2</li>\n    <li>Item 3</li>\n    <li class=\"disabled\">Item 4</li>\n    <li class=\"disabled\">Item 5</li>\n    <li class=\"disabled\">Item 6</li>\n  </ul>\n</section>",
    sortableWithHandles: "<section id=\"sortable-with-handles\">\n  <h2>Sortable With Handles</h2>\n  <ul class=\"sortable sortable-with-handles\">\n    <li><span>::</span> Item 1</li>\n    <li><span>::</span> Item 2</li>\n    <li><span>::</span> Item 3</li>\n    <li><span>::</span> Item 4</li>\n    <li><span>::</span> Item 5</li>\n    <li><span>::</span> Item 6</li>\n  </ul>\n</section>",
    sortableConnected: "<section id=\"sortable-connected\">\n  <h2>Sortable With Connected</h2>\n  <ul class=\"sortable sortable-connected sortable-connected-1\">\n    <li>Item 1</li>\n    <li>Item 2</li>\n    <li>Item 3</li>\n    <li>Item 4</li>\n    <li>Item 5</li>\n    <li>Item 6</li>\n  </ul>\n  <ul class=\"sortable sortable-connected sortable-connected-2\">\n    <li class=\"highlight\">Item 1</li>\n    <li class=\"highlight\">Item 2</li>\n    <li class=\"highlight\">Item 3</li>\n    <li class=\"highlight\">Item 4</li>\n    <li class=\"highlight\">Item 5</li>\n    <li class=\"highlight\">Item 6</li>\n  </ul>\n</section>"
  };

  window.TestHelper = {
    fixture: function(name) {
      return _fixtureSrings[name];
    },
    loadFixture: function(name) {
      var html, newEle;
      html = this.fixture(name);
      newEle = this.cleanSandbox();
      newEle.html(html);
      return newEle;
    },
    cleanSandbox: function() {
      var id, newEle, oldEle;
      id = 'sandbox';
      oldEle = document.getElementById(id);
      if (oldEle) {
        oldEle.parentNode.removeChild(oldEle);
      }
      newEle = document.createElement('div');
      newEle.id = id;
      document.body.appendChild(newEle);
      return $(newEle);
    }
  };

}).call(this);
