// Generated by CoffeeScript 1.4.0

/*
 HTML5 Sortable jQuery Plugin
 http://farhadi.ir/projects/html5sortable
 
 Copyright 2012, Ali Farhadi
 Released under the MIT license.
*/


(function() {
  var $;

  $ = this.jQuery || this.Zepto;

}).call(this);
